import Head from "next/head";
import { useState, useEffect } from "react";
import "bootstrap/dist/css/bootstrap.min.css";

export default function Home() {
    const [url, setUrl] = useState("");
    const [shortened, setShortened] = useState("");

    async function checkIt() {
        try {
            const res = await fetch(`/api/urls?original=${window.location.href}`);
            const json = await res.json();

            if (res.ok) {
                const { original } = json;
                window.location.href = original;
            } else {
                throw new Error(json.message);
            }
        } catch (error) {
            alert((error as unknown as Error).message);
        }
    }

    async function createShortenedURL(e: React.MouseEvent<HTMLButtonElement>) {
        e.preventDefault();
        try {
            const res = await fetch(`/api/urls`, {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({ original: url }),
            });
            const json = await res.json();

            if (res.ok) {
                const { url } = json;
                setShortened(url);
            } else {
                throw new Error(json.message);
            }
        } catch (error) {
            alert((error as unknown as Error).message);
        }
    }

    useEffect(() => {
        document.body.style.backgroundColor = "#d4d4d4";
        if (window.location.href.includes("?u=")) {
            checkIt();
        }
    }, []);

    return (
        <>
            <Head>
                <title>chrome-setup.zip</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="container">
                <div className="row mt-5 justify-content-center">
                    <div className="col-12 col-md-9 col-lg-8 mt-5">
                        <form style={{ backgroundColor: "#9999ff" }} className="rounded-3 shadow p-3">
                            <h1 className="text-center text-light">chrome-setup.zip</h1>
                            {shortened && <a href={shortened}>{shortened}</a>}
                            <div className="row">
                                <div className="col-12 col-md-9">
                                    <input
                                        className="form-control"
                                        value={url}
                                        onChange={(e) => setUrl(e.target.value)}
                                        type="text"
                                    />
                                </div>
                                <div className="col-12 col-md-3">
                                    <button
                                        onClick={createShortenedURL}
                                        style={{ backgroundColor: "#bbbbff" }}
                                        className="btn"
                                    >
                                        Shorten!
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </main>
        </>
    );
}
